# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: aeropuerto.proto for package 'aeropuerto'

require 'grpc'
require 'aeropuerto_pb'

module Aeropuerto
  module Aeropuerto
    # Servicio Aeropuerto
    # 
    # Pedir aterrizaje: Solicitud de aterrizaje por parte del avion.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'aeropuerto.Aeropuerto'

      rpc :Pedir_Aterrizaje, AtRequest, AtReply
    end

    Stub = Service.rpc_stub_class
  end
end
