# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aeropuerto.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "aeropuerto.AtRequest" do
    optional :nombre, :string, 1
    optional :proveniente, :string, 2
  end
  add_message "aeropuerto.AtReply" do
    optional :respuesta, :int32, 1
    optional :pista, :int32, 2
    optional :altura, :int32, 3
    optional :pos_cola, :int32, 4
  end
end

module Aeropuerto
  AtRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("aeropuerto.AtRequest").msgclass
  AtReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("aeropuerto.AtReply").msgclass
end
