# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aeropuerto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aeropuerto.proto',
  package='aeropuerto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x61\x65ropuerto.proto\x12\naeropuerto\"0\n\tAtRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x13\n\x0bproveniente\x18\x02 \x01(\t\"M\n\x07\x41tReply\x12\x11\n\trespuesta\x18\x01 \x01(\x05\x12\r\n\x05pista\x18\x02 \x01(\x05\x12\x0e\n\x06\x61ltura\x18\x03 \x01(\x05\x12\x10\n\x08pos_cola\x18\x04 \x01(\x05\"}\n\nDesRequest\x12\x13\n\x0b\x63ombustible\x18\x01 \x01(\x05\x12\x17\n\x0f\x63ombustible_max\x18\x02 \x01(\x05\x12\r\n\x05\x63\x61rga\x18\x03 \x01(\x05\x12\x11\n\tcarga_max\x18\x04 \x01(\x05\x12\x0f\n\x07\x64\x65stino\x18\x05 \x01(\t\x12\x0e\n\x06nombre\x18\x06 \x01(\t\"i\n\x08\x44\x65sReply\x12\x11\n\trespuesta\x18\x01 \x01(\x05\x12\r\n\x05pista\x18\x02 \x01(\x05\x12\x0e\n\x06\x61ltura\x18\x03 \x01(\x05\x12\x14\n\x0cnombre_torre\x18\x04 \x01(\t\x12\x15\n\rtorre_control\x18\x05 \x01(\t2\xdf\x01\n\nAeropuerto\x12@\n\x10Pedir_Aterrizaje\x12\x15.aeropuerto.AtRequest\x1a\x13.aeropuerto.AtReply\"\x00\x12I\n\x19Pedir_Aterrizaje_Encolado\x12\x15.aeropuerto.AtRequest\x1a\x13.aeropuerto.AtReply\"\x00\x12\x44\n\x12Solicitar_despegue\x12\x16.aeropuerto.DesRequest\x1a\x14.aeropuerto.DesReply\"\x00\x62\x06proto3')
)




_ATREQUEST = _descriptor.Descriptor(
  name='AtRequest',
  full_name='aeropuerto.AtRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='aeropuerto.AtRequest.nombre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proveniente', full_name='aeropuerto.AtRequest.proveniente', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=80,
)


_ATREPLY = _descriptor.Descriptor(
  name='AtReply',
  full_name='aeropuerto.AtReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='respuesta', full_name='aeropuerto.AtReply.respuesta', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pista', full_name='aeropuerto.AtReply.pista', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altura', full_name='aeropuerto.AtReply.altura', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_cola', full_name='aeropuerto.AtReply.pos_cola', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=159,
)


_DESREQUEST = _descriptor.Descriptor(
  name='DesRequest',
  full_name='aeropuerto.DesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='combustible', full_name='aeropuerto.DesRequest.combustible', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='combustible_max', full_name='aeropuerto.DesRequest.combustible_max', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='carga', full_name='aeropuerto.DesRequest.carga', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='carga_max', full_name='aeropuerto.DesRequest.carga_max', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destino', full_name='aeropuerto.DesRequest.destino', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nombre', full_name='aeropuerto.DesRequest.nombre', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=286,
)


_DESREPLY = _descriptor.Descriptor(
  name='DesReply',
  full_name='aeropuerto.DesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='respuesta', full_name='aeropuerto.DesReply.respuesta', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pista', full_name='aeropuerto.DesReply.pista', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altura', full_name='aeropuerto.DesReply.altura', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nombre_torre', full_name='aeropuerto.DesReply.nombre_torre', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torre_control', full_name='aeropuerto.DesReply.torre_control', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=393,
)

DESCRIPTOR.message_types_by_name['AtRequest'] = _ATREQUEST
DESCRIPTOR.message_types_by_name['AtReply'] = _ATREPLY
DESCRIPTOR.message_types_by_name['DesRequest'] = _DESREQUEST
DESCRIPTOR.message_types_by_name['DesReply'] = _DESREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AtRequest = _reflection.GeneratedProtocolMessageType('AtRequest', (_message.Message,), dict(
  DESCRIPTOR = _ATREQUEST,
  __module__ = 'aeropuerto_pb2'
  # @@protoc_insertion_point(class_scope:aeropuerto.AtRequest)
  ))
_sym_db.RegisterMessage(AtRequest)

AtReply = _reflection.GeneratedProtocolMessageType('AtReply', (_message.Message,), dict(
  DESCRIPTOR = _ATREPLY,
  __module__ = 'aeropuerto_pb2'
  # @@protoc_insertion_point(class_scope:aeropuerto.AtReply)
  ))
_sym_db.RegisterMessage(AtReply)

DesRequest = _reflection.GeneratedProtocolMessageType('DesRequest', (_message.Message,), dict(
  DESCRIPTOR = _DESREQUEST,
  __module__ = 'aeropuerto_pb2'
  # @@protoc_insertion_point(class_scope:aeropuerto.DesRequest)
  ))
_sym_db.RegisterMessage(DesRequest)

DesReply = _reflection.GeneratedProtocolMessageType('DesReply', (_message.Message,), dict(
  DESCRIPTOR = _DESREPLY,
  __module__ = 'aeropuerto_pb2'
  # @@protoc_insertion_point(class_scope:aeropuerto.DesReply)
  ))
_sym_db.RegisterMessage(DesReply)



_AEROPUERTO = _descriptor.ServiceDescriptor(
  name='Aeropuerto',
  full_name='aeropuerto.Aeropuerto',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=396,
  serialized_end=619,
  methods=[
  _descriptor.MethodDescriptor(
    name='Pedir_Aterrizaje',
    full_name='aeropuerto.Aeropuerto.Pedir_Aterrizaje',
    index=0,
    containing_service=None,
    input_type=_ATREQUEST,
    output_type=_ATREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Pedir_Aterrizaje_Encolado',
    full_name='aeropuerto.Aeropuerto.Pedir_Aterrizaje_Encolado',
    index=1,
    containing_service=None,
    input_type=_ATREQUEST,
    output_type=_ATREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Solicitar_despegue',
    full_name='aeropuerto.Aeropuerto.Solicitar_despegue',
    index=2,
    containing_service=None,
    input_type=_DESREQUEST,
    output_type=_DESREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AEROPUERTO)

DESCRIPTOR.services_by_name['Aeropuerto'] = _AEROPUERTO

# @@protoc_insertion_point(module_scope)
