# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aeropuerto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aeropuerto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x61\x65ropuerto.proto\"0\n\tAtRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x13\n\x0bproveniente\x18\x02 \x01(\t\"M\n\x07\x41tReply\x12\x11\n\trespuesta\x18\x01 \x01(\x05\x12\r\n\x05pista\x18\x02 \x01(\x05\x12\x0e\n\x06\x61ltura\x18\x03 \x01(\x05\x12\x10\n\x08pos_cola\x18\x04 \x01(\x05\x32\x38\n\nAeropuerto\x12*\n\x10Pedir_Aterrizaje\x12\n.AtRequest\x1a\x08.AtReply\"\x00\x62\x06proto3')
)




_ATREQUEST = _descriptor.Descriptor(
  name='AtRequest',
  full_name='AtRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='AtRequest.nombre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proveniente', full_name='AtRequest.proveniente', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=68,
)


_ATREPLY = _descriptor.Descriptor(
  name='AtReply',
  full_name='AtReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='respuesta', full_name='AtReply.respuesta', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pista', full_name='AtReply.pista', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altura', full_name='AtReply.altura', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_cola', full_name='AtReply.pos_cola', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['AtRequest'] = _ATREQUEST
DESCRIPTOR.message_types_by_name['AtReply'] = _ATREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AtRequest = _reflection.GeneratedProtocolMessageType('AtRequest', (_message.Message,), dict(
  DESCRIPTOR = _ATREQUEST,
  __module__ = 'aeropuerto_pb2'
  # @@protoc_insertion_point(class_scope:AtRequest)
  ))
_sym_db.RegisterMessage(AtRequest)

AtReply = _reflection.GeneratedProtocolMessageType('AtReply', (_message.Message,), dict(
  DESCRIPTOR = _ATREPLY,
  __module__ = 'aeropuerto_pb2'
  # @@protoc_insertion_point(class_scope:AtReply)
  ))
_sym_db.RegisterMessage(AtReply)



_AEROPUERTO = _descriptor.ServiceDescriptor(
  name='Aeropuerto',
  full_name='Aeropuerto',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=149,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='Pedir_Aterrizaje',
    full_name='Aeropuerto.Pedir_Aterrizaje',
    index=0,
    containing_service=None,
    input_type=_ATREQUEST,
    output_type=_ATREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AEROPUERTO)

DESCRIPTOR.services_by_name['Aeropuerto'] = _AEROPUERTO

# @@protoc_insertion_point(module_scope)
